temp

diff --git a/scripts/git-hooks/pre-commit b/scripts/git-hooks/pre-commit
--- a/scripts/git-hooks/pre-commit
+++ b/scripts/git-hooks/pre-commit
@@ -24,5 +24,7 @@ done
 
 if [ $exit_status -ne 0 ]
 then
-    echo "MyPy returned some errors, please correct them before pushing your code"
+    echo "MyPy returned some errors, please correct them"
+    echo "Commit aborted"
+    #exit 1
 fi
