removed generated files

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -1,79 +1,59 @@
-
-##################################################################################
-# 
-# This file is automatically generated using templates. Changes to this file
-# should happen through editing the templates under .action_templates/*
-# Manual edits will be overwritten.
-#
-##################################################################################
-
 name: Run E2E
 on:
-  # template: .action_templates/events/on-pull-request-master.yaml
   pull_request:
     branches:
-    - master
-    paths-ignore:
-    - docs/**
-  # template: .action_templates/events/on-push-master.yaml
+      - master
   push:
     branches:
-    - master
-    paths-ignore:
-    - docs/**
-  # template: .action_templates/events/workflow-dispatch.yaml
-  workflow_dispatch: {}
+      - master
+  workflow_dispatch:
 jobs:
-  # template: .action_templates/jobs/setup.yaml
   setup:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         include:
-        - pipeline-argument: operator-ubi
-        - pipeline-argument: version-post-start-hook-init
-        - pipeline-argument: readiness-probe-init
-        - pipeline-argument: agent-ubi
-        - pipeline-argument: agent-ubuntu
-        - pipeline-argument: e2e
-    if: github.event.pull_request.head.repo.full_name == 'mongodb/mongodb-kubernetes-operator'
+          - pipeline-argument: operator-ubi
+          - pipeline-argument: version-post-start-hook-init
+          - pipeline-argument: readiness-probe-init
+          - pipeline-argument: agent-ubi
+          - pipeline-argument: agent-ubuntu
+          - pipeline-argument: e2e
     steps:
-    # template: .action_templates/steps/cancel-previous.yaml
-    - name: Cancel Previous Runs
-      uses: styfle/cancel-workflow-action@0.9.0
-      with:
-        access_token: ${{ github.token }}
-    # template: .action_templates/steps/checkout.yaml
-    - name: Checkout Code
-      uses: actions/checkout@v2
-    # template: .action_templates/steps/setup-and-install-python.yaml
-    - name: Setup Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.8'
-    - name: Cache Dependencies
-      uses: actions/cache@v2
-      with:
-        path: ~/.cache/pip
-        key: ${{ hashFiles('requirements.txt') }}
-    - name: Install Python Dependencies
-      run: pip install -r requirements.txt
-    # template: .action_templates/steps/quay-login.yaml
-    - name: Login to Quay.io
-      uses: docker/login-action@v1
-      with:
-        registry: quay.io
-        username: ${{ secrets.QUAY_USERNAME }}
-        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
-    # template: .action_templates/steps/build-and-push-development-images.yaml
-    - name: Build and Push Images
-      run: |
-        python pipeline.py --image-name ${{ matrix.pipeline-argument }} --release false
-      env:
-        MONGODB_COMMUNITY_CONFIG: ${{ github.workspace }}/scripts/ci/config.json
-        version_id: ${{ github.run_id }}
-  # template: .action_templates/jobs/tests.yaml
+      - name: Cancel Previous Runs
+        uses: styfle/cancel-workflow-action@0.9.0
+        with:
+          access_token: ${{ github.token }}
+
+      - name: Checkout Code
+        uses: actions/checkout@v2
+      - name: Setup Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.8'
+
+      - uses: actions/cache@v2
+        with:
+          path: ~/.cache/pip
+          key: ${{ hashFiles('requirements.txt') }}
+
+      - name: Install Python Dependencies
+        run: pip install -r requirements.txt
+
+      - name: Login to Quay.io
+        uses: docker/login-action@v1
+        with:
+          registry: quay.io
+          username: ${{ secrets.QUAY_USERNAME }}
+          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
+
+      - name: Build and Push Images
+        run: python pipeline.py --image-name ${{ matrix.pipeline-argument }} --release false
+        env:
+          MONGODB_COMMUNITY_CONFIG: "${{ github.workspace }}/scripts/ci/config.json"
+          version_id: "${{ github.run_id }}"
+
   tests:
     runs-on: ubuntu-latest
     needs: [setup]
@@ -81,161 +61,163 @@ jobs:
       fail-fast: false
       matrix:
         include:
-        - test-name: replica_set
-          distro: ubuntu
-        - test-name: replica_set_recovery
-          distro: ubuntu
-        - test-name: replica_set_recovery
-          distro: ubuntu
-        - test-name: replica_set_mongod_readiness
-          distro: ubuntu
-        - test-name: replica_set_scale
-          distro: ubuntu
-        - test-name: replica_set_scale_down
-          distro: ubuntu
-        - test-name: replica_set_change_version
-          distro: ubuntu
-        - test-name: feature_compatibility_version
-          distro: ubuntu
-        - test-name: feature_compatibility_version_upgrade
-          distro: ubuntu
-        - test-name: replica_set_tls
-          distro: ubuntu
-        - test-name: replica_set_tls_upgrade
-          distro: ubuntu
-        - test-name: statefulset_arbitrary_config
-          distro: ubuntu
-        - test-name: statefulset_arbitrary_config_update
-          distro: ubuntu
-        - test-name: replica_set_mongod_config
-          distro: ubuntu
-        - test-name: replica_set_cross_namespace_deploy
-          distro: ubuntu
-          cluster-wide: true
-        - test-name: replica_set_custom_role
-          distro: ubuntu
-        - test-name: replica_set_arbiter
-          distro: ubuntu
+          - test-name: replica_set
+            distro: ubuntu
+          - test-name: replica_set_recovery
+            distro: ubuntu
+          - test-name: replica_set_recovery
+            distro: ubuntu
+          - test-name: replica_set_mongod_readiness
+            distro: ubuntu
+          - test-name: replica_set_scale
+            distro: ubuntu
+          - test-name: replica_set_scale_down
+            distro: ubuntu
+          - test-name: replica_set_change_version
+            distro: ubuntu
+          - test-name: feature_compatibility_version
+            distro: ubuntu
+          - test-name: feature_compatibility_version_upgrade
+            distro: ubuntu
+          - test-name: replica_set_tls
+            distro: ubuntu
+          - test-name: replica_set_tls_upgrade
+            distro: ubuntu
+          - test-name: statefulset_arbitrary_config
+            distro: ubuntu
+          - test-name: statefulset_arbitrary_config_update
+            distro: ubuntu
+          - test-name: replica_set_mongod_config
+            distro: ubuntu
+          - test-name: replica_set_cross_namespace_deploy
+            distro: ubuntu
+            cluster-wide: true
+          - test-name: replica_set_custom_role
+            distro: ubuntu
+          - test-name: replica_set_arbiter
+            distro: ubuntu
 
-        - test-name: replica_set
-          distro: ubi
-        - test-name: replica_set_recovery
-          distro: ubi
-        - test-name: replica_set_recovery
-          distro: ubi
-        - test-name: replica_set_mongod_readiness
-          distro: ubi
-        - test-name: replica_set_scale
-          distro: ubi
-        - test-name: replica_set_scale_down
-          distro: ubi
-        - test-name: replica_set_change_version
-          distro: ubi
-        - test-name: feature_compatibility_version
-          distro: ubi
-        - test-name: feature_compatibility_version_upgrade
-          distro: ubi
-        - test-name: replica_set_tls
-          distro: ubi
-        - test-name: replica_set_tls_upgrade
-          distro: ubi
-        - test-name: statefulset_arbitrary_config
-          distro: ubi
-        - test-name: statefulset_arbitrary_config_update
-          distro: ubi
-        - test-name: replica_set_mongod_config
-          distro: ubi
-        - test-name: replica_set_cross_namespace_deploy
-          distro: ubi
-          cluster-wide: true
-        - test-name: replica_set_custom_role
-          distro: ubi
-        - test-name: replica_set_arbiter
-          distro: ubi
+          - test-name: replica_set
+            distro: ubi
+          - test-name: replica_set_recovery
+            distro: ubi
+          - test-name: replica_set_recovery
+            distro: ubi
+          - test-name: replica_set_mongod_readiness
+            distro: ubi
+          - test-name: replica_set_scale
+            distro: ubi
+          - test-name: replica_set_scale_down
+            distro: ubi
+          - test-name: replica_set_change_version
+            distro: ubi
+          - test-name: feature_compatibility_version
+            distro: ubi
+          - test-name: feature_compatibility_version_upgrade
+            distro: ubi
+          - test-name: replica_set_tls
+            distro: ubi
+          - test-name: replica_set_tls_upgrade
+            distro: ubi
+          - test-name: statefulset_arbitrary_config
+            distro: ubi
+          - test-name: statefulset_arbitrary_config_update
+            distro: ubi
+          - test-name: replica_set_mongod_config
+            distro: ubi
+          - test-name: replica_set_cross_namespace_deploy
+            distro: ubi
+            cluster-wide: true
+          - test-name: replica_set_custom_role
+            distro: ubi
+          - test-name: replica_set_arbiter
+            distro: ubi
+
+
     steps:
-    # template: .action_templates/steps/cancel-previous.yaml
-    - name: Cancel Previous Runs
-      uses: styfle/cancel-workflow-action@0.9.0
-      with:
-        access_token: ${{ github.token }}
-    # template: .action_templates/steps/checkout.yaml
-    - name: Checkout Code
-      uses: actions/checkout@v2
-    # template: .action_templates/steps/set-run-status.yaml
-    - name: Set default run status
-      run: echo "::set-output name=last_run_status::pending" > last_run_status
+      - name: Cancel Previous Runs
+        uses: styfle/cancel-workflow-action@0.9.0
+        with:
+          access_token: ${{ github.token }}
 
-  # Tracking of the state of the previous test run is a workaround to the fact that it is not
-  # possible to re-run a single failed job, only re-running the entire workflow is currently possible.
-  # This workaround skips jobs if they have already passed.
-  # see https://github.com/actions/runner/issues/432
-    - name: Restore last run status
-      id: last_run
-      uses: actions/cache@v2
-      with:
-        path: last_run_status
-        key: ${{ github.run_id }}-${{ matrix.test-name }}-${{ matrix.distro }}
+      - name: Checkout Code
+        uses: actions/checkout@v2
 
-    - name: Set last run status
-      id: last_run_status
-      run: cat last_run_status
-    # template: .action_templates/steps/setup-and-install-python.yaml
-    - name: Setup Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.8'
-    - name: Cache Dependencies
-      uses: actions/cache@v2
-      with:
-        path: ~/.cache/pip
-        key: ${{ hashFiles('requirements.txt') }}
-    - name: Install Python Dependencies
-      run: pip install -r requirements.txt
-    # template: .action_templates/steps/setup-kind-cluster.yaml
-    - name: Setup Kind Cluster
-      uses: engineerd/setup-kind@v0.5.0
-      with:
-        version: v0.8.1
+      - name: Set default run status
+        run: echo "::set-output name=last_run_status::pending" > last_run_status
 
-      if: steps.last_run_status.outputs.last_run_status != 'success'
-    - name: Install CRD
-      run: kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
-      if: steps.last_run_status.outputs.last_run_status != 'success'
-    # template: .action_templates/steps/run-test-matrix.yaml
-    - name: Run Test
-      id: e2e_test
-      if: steps.last_run_status.outputs.last_run_status != 'success'
-      run: |
-        cluster_wide=${{ matrix.cluster-wide }}
-        if [ -z "$cluster_wide" ]; then
-          cluster_wide="false"
-        fi
-        python3 ./scripts/dev/e2e.py --test ${{ matrix.test-name }} --tag ${{ github.run_id }} --config_file ./scripts/ci/config.json --distro ${{ matrix.distro }} --cluster-wide ${cluster_wide}
-    # template: .action_templates/steps/save-run-status.yaml
-    - name: Save run status
-      if: always()
-      run: echo "::set-output name=last_run_status::${{ steps.e2e_test.outcome }}"
-        > last_run_status
-    # template: .action_templates/steps/dump-and-upload-diagnostics.yaml
-    - name: Dump Diagnostics
-      id: dump_diagnostics
-      if: always() && steps.e2e_test.outcome == 'failure'
-      continue-on-error: true
-      run: scripts/ci/dump_diagnostics.sh default # default since kind is running in the default namespace
+        # Tracking of the state of the previous test run is a workaround to the fact that it is not
+        # possible to re-run a single failed job, only re-running the entire workflow is currently possible.
+        # This workaround skips jobs if they have already passed.
+        # see https://github.com/actions/runner/issues/432
+      - name: Restore last run status
+        id: last_run
+        uses: actions/cache@v2
+        with:
+          path: last_run_status
+          key: ${{ github.run_id }}-${{ matrix.test-name }}-${{ matrix.distro }}
 
-    - name: Upload Diagnostics
-      if: always() && steps.dump_diagnostics.outcome == 'success'
-      uses: actions/upload-artifact@v2
-      continue-on-error: true
-      with:
-        name: ${{ matrix.test-name }}-${{ matrix.distro }}-diagnostics
-        path: ${{ github.workspace }}/diagnostics
-  # template: .action_templates/jobs/e2e-success.yaml
+      - name: Set last run status
+        id: last_run_status
+        run: cat last_run_status
+
+      - name: Setup Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.8'
+
+      - name: Cache Dependencies
+        uses: actions/cache@v2
+        with:
+          path: ~/.cache/pip
+          key: ${{ hashFiles('requirements.txt') }}
+
+      - name: Install Python Dependencies
+        run: pip install -r requirements.txt
+
+      - name: Setup Kind Cluster
+        if: steps.last_run_status.outputs.last_run_status != 'success'
+        uses: engineerd/setup-kind@v0.5.0
+        with:
+          version: "v0.8.1"
+
+      - name: Install CRD
+        if: steps.last_run_status.outputs.last_run_status != 'success'
+        run: kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
+
+      - name: Run Test
+        id: e2e_test
+        if: steps.last_run_status.outputs.last_run_status != 'success'
+        run: |
+          cluster_wide=${{ matrix.cluster-wide }}
+          if [ -z "$cluster_wide" ]; then
+            cluster_wide="false"
+          fi
+          python3 ./scripts/dev/e2e.py --test ${{ matrix.test-name }} --tag ${{ github.run_id }} --config_file ./scripts/ci/config.json --distro ${{ matrix.distro }} --cluster-wide ${cluster_wide}
+
+      - name: Save run status
+        if: always()
+        run: echo "::set-output name=last_run_status::${{ steps.e2e_test.outcome }}" > last_run_status
+
+      - name: Dump Diagnostics
+        id: dump_diagnostics
+        if: always() && steps.e2e_test.outcome == 'failure'
+        continue-on-error: true
+        run: scripts/ci/dump_diagnostics.sh default # default since kind is running in the default namespace
+
+      - name: Upload Diagnostics
+        if: always() && steps.dump_diagnostics.outcome == 'success'
+        uses: actions/upload-artifact@v2
+        continue-on-error: true
+        with:
+          name: "${{ matrix.test-name }}-${{ matrix.distro }}-diagnostics"
+          path: "${{ github.workspace }}/diagnostics"
+
   e2e-success:
     if: always()
     needs: [tests]
     runs-on: ubuntu-latest
     steps:
-    - name: Check E2E Result
-      if: needs.tests.result != 'success'
-      run: exit 1
+      - name: Check E2E Result
+        if: needs.tests.result != 'success'
+        run: exit 1
